# Generated by Django 4.2 on 2023-04-10 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='choosus',
            new_name='team',
        ),
    ]
